marcelm/dnaio

src/dnaio/_core.pyx
I checked if `.decode('ascii')` could be used as a shorthand to check whether these strings are valid ASCII. It is possible but it comes at a speed disadvantage
```
Benchmark #1: python dnaio_read.py ~/test/big2.fastq
Time (mean ± σ):      1.958 s ±  0.050 s    [User: 1.843 s, System: 0.114 s]
Range (min … max):    1.918 s …  2.094 s    10 runs
Benchmark #1: python dnaio_read.py ~/test/big2.fastq
Time (mean ± σ):      2.311 s ±  0.076 s    [User: 2.196 s, System: 0.115 s]
Range (min … max):    2.256 s …  2.507 s    10 runs
```
I dived deeper in the Python code and put my findings in the comments as to why this is.
=> Add more explanation about the decode('latin-1') speed advantage

src/dnaio/readers.py
Sorry for the PR spam. I found some minor things in the code that each should be considered in isolation.
This is the size used by cat and pigz to read files. This uses less memory. No performance impact on normal files. Faster on reading from pipes.
before:
```
Benchmark #1: python dnaio_read.py ~/test/big2.fastq
Time (mean ± σ):      2.075 s ±  0.031 s    [User: 1.953 s, System: 0.122 s]
Range (min … max):    2.012 s …  2.145 s    20 runs
```
After:
```
Benchmark #1: python dnaio_read.py ~/test/big2.fastq
Time (mean ± σ):      2.067 s ±  0.021 s    [User: 1.946 s, System: 0.121 s]
Range (min … max):    2.030 s …  2.113 s    20 runs
```
Gzip files:
Before:
```
Benchmark #1: python dnaio_read.py ~/test/big2.fastq.gz
Time (mean ± σ):      3.417 s ±  0.045 s    [User: 5.089 s, System: 0.560 …
```
=> Decrease buffer size to 128KiB to improve performance when reading from pipes.

src/dnaio/_core.pyx
When calling `__new__`, the `__cinit__` method is called, but the `__init__` method is not. Since we have already checked the length of the sequence in the `fastq_iter` method there is no need to check the length again in the `__cinit__` method.
This speeds up the parsing slightly (benchmarks in conjunction with #14):
before:
```
Benchmark #1: python dnaio_read.py ~/test/big2.fastq
Time (mean ± σ):      1.081 s ±  0.023 s    [User: 966.8 ms, System: 114.1 ms]
Range (min … max):    1.041 s …  1.147 s    50 runs
```
after:
```
Benchmark #1: python dnaio_read.py ~/test/big2.fastq
Time (mean ± σ):      1.050 s ±  0.027 s    [User: 938.7 ms, System: 111.4 ms]
Range (min … max):    1.003 s …  1.121 s    50 runs
```
The speed increase is small but many small changes can amount to something.
=> Move length check to __init__ method of sequence

src/dnaio/_core.pyx, tests/test_internal.py
I noticed that paired end reading incurs a heavy performance penalty
Baseline:
```
Benchmark #1: python dnaio_read_paired.py ~/test/big2.fastq
Time (mean ± σ):      5.693 s ±  0.026 s    [User: 5.480 s, System: 0.213 s]
Range (min … max):    5.650 s …  5.737 s    10 runs
```
Given that in single-end mode it runs in 2.1 seconds, this is quite heavy. 
So I disabled the namecheck to see what the difference would be:
```
Benchmark #1: python dnaio_read_paired.py ~/test/big2.fastq
Time (mean ± σ):      4.491 s ±  0.025 s    [User: 4.268 s, System: 0.223 s]
Range (min … max):    4.443 s …  4.538 s    10 runs
```
So that is roughly 1.3 seconds extra. Just for the name checking. That is rather suboptimal. We can parse the entire file again in that time.  (NOTE that this PR originates from main, …
=> Increase speed of name matching for paired end reads.

.github/workflows/ci.yml, pyproject.toml, setup.cfg, setup.py, tox.ini
- Move metadata to `setup.cfg`
- Add a CI test that runs `python -m build`, which will build the sdist and create a wheel from it. This ensures that the sdist contains all files necessary to build the wheel
- Expect Cython to be installed at build time and just always call `cythonize()`. Because of this, there’s no need for custom `build_ext` nor `sdist` classes anymore.
- With `isolated_build = True` in `tox.ini`, the build dependencies only need to specify once, in `pyproject.toml`.
I made most of these changes previously in WhatsHap, see https://github.com/whatshap/whatshap/pull/344, and also in Cutadapt.
Supercedes #16
=> Modernize setup

src/dnaio/pairedend.py, tests/test_internal.py
Sorry for the PR spam. I just suddenly find so much stuff to optimize in this library. And even more is coming, but that depends on still pending PRs #14 and #20. (I want to make writing faster still, by avoiding creating new bytes objects).
This is an easy one to review. I know you are busy!
Ideally we would want to use `zip(it1, it2, strict=True)`, but that is only available from python 3.10 and higher. (3.9 on my Debian 11 machine).
Since try ... except has some expense I tried using `next` differently. It has a default argument. So you can use `next(it1, None)` and it will yield None if the iterator is exhausted. This leads to a cleaner looking code when checking.
I had a look at itertools if there was something in the standard library, and yes there was: zip_longest. Keeps on …
=> Use zip_longest for more readable and faster code in the paired end iterator

.github/workflows/ci.yml, setup.cfg, src/dnaio/singleend.py, tests/test_internal.py
- The GitHub Actions job that created the wheels needed to become a matrix job that runs on Windows and Linux. Because the sdist was also created in that job and I did not want it to be created multiple times, sdist creation, wheel creation and publishing are now separate jobs.
- `pipx` is installed on the Linux runners, so building the sdist could be simplified to `pipx run build` (and to test whether a wheel can be created from the sdist, I do not add the `--sdist` option).
- The other changes were just the things necessary to make the code work on both platforms.
- The Windows tests should no longer fail as soon as https://github.com/pycompression/xopen/pull/83 is merged and a new xopen version is published.
=> Support Windows

src/dnaio/chunks.py, tests/test_chunks.py
See https://github.com/marcelm/cutadapt/issues/591.
The FASTA parser allows comment lines in FASTA (starting with `#`), but the `_fasta_head` function does not take this into account.
This also makes some error messages somewhat more informative.
=> Fix parsing of FASTA files that contain a comment and no reads

src/dnaio/_core.pyx
This avoids some of the overhead of calling `PyUnicode_DecodeLatin1` by creating the unicode object with an unitialized buffer and then copying the data into it.
On my test data, this gives a ~9% speedup for the `for r in dnaio.open("r.fastq"): pass` loop (2.42 seconds to 2.20 seconds).
This is marked as draft because PyUnicode_New can return NULL, in which case we need to raise a `MemoryError()` (this is also done incorrectly in some other places in the code).
I have no idea whether this is done correctly. For example, `PyUnicode_New` actually returns a `PyObject*`, but I only got it to work by declaring it as returning `object`.
=> Construct unicode objects with PyUnicode_New

MANIFEST.in, pyproject.toml, setup.cfg, setup.py
fixes #50 
This removes the `cythonize` command from setup.py. Cythonize gives more control over how to cythonize extensions, but this is already covered in the `_core.pyx` file itself as it has the compiler_directives set there.
The disadvantage of `cythonize` is that it converts a cython extension into a distutils.Extension. In other words a normal C-extension. Therefore setuptools thinks that the C-source should be included. 
Setuptools.Extension however does recognize `.pyx` files and will convert them to C files itself. So there is no need for cythonize. By this way setuptools realizes that the source file is not the C file but the `.pyx` file and will therefore only include the pyx file.
I also struck the C file from the manifest. Both the Setuptools.Extension and the MANIFEST.in …
=> Do not ship C file in source distribution

MANIFEST.in
When setuptools_scm is installed, it provides some kind of a "file finder" plugin for setuptools that includes all files under version control in the sdist.
This is somewhat suprising to me, but we might as well rely on that behavior.
`src/dnaio/_version.py` is explicitly gitignore-d, but I tested it and saw that it is included in the sdist.
Also, `README.md` was incorrect anyway as we renamed the file to `README.rst` recently.
=> MANIFEST.in is not needed

src/dnaio/_core.pyi, src/dnaio/_core.pyx, tests/test_internal.py
Same as for Sequence. I added more stringent checks on BytesSequence getters and setters so None is not allowed for name and sequence.
I also copied and modified some docstrings.
=> Bytes object touchups: no None, docstrings.

src/dnaio/readers.py, tests/test_internal.py, tests/test_open.py
This should fix the test failures in marcelm/cutadapt#609.
Possibly we should start to treat these warnings as errors just as in Cutadapt. I was a bit undisciplined with closing files in Cutadapt in the beginning, but then this actually led to truncated files that a user reported. Since then, I try to heed these warnings and close everything properly (so not relying on automatic cleanup at process termination).
=> Avoid some "unclosed file" ResourceWarnings

src/dnaio/ascii_check.h
This is 20% faster for the ascii check. But 20% faster on something that is not a bottleneck is not really noticable. Still, I don't like wasting compute cycles and this makes the code simpler and without branches. 
I have been fiddling a bit with the ascii-check repo. I also added an SSE2 implementation in that repo. SSE2 in particular is a **very** interesting instruction set because **all** x86-64 CPUs support it. No exceptions. So it can always be included in the x86-64 builds. 
That implementation cuts the ASCII checking time in more than half, so that might be interesting to look at. I will add that later after this is merged.
=> Branchless checking for ASCII

setup.py, src/dnaio/_core.pyx, src/dnaio/ascii_check_sse2.h
SSE2 is guaranteed to be present on al AMD64 (x86_64) platforms. So a simple check for such a platform is sufficient to enable the instruction set without running into compile problems.
This increases the ASCII check speed from 20GB/s to 50GB/s. Making our ASCII string cost creation almost free.
=> Vectorize the ASCII check using SSE2 instructions

src/dnaio/_core.pyx
This removes some redundant variables as well as making quite a few lines of code shorter. It also reduces the amount of pointer arithmetic. (Much less `self.buffer + some_offset`.) 
Additionally all the "pointer slicing" (was exclusively used in errors) has been replaced with the appropriate calls to PyUnicode_DecodeASCII.
PyUnicode_1BYTE_DATA has been replaced with PyUnicode_DATA. Since we cast the results to `<char *>` anyway
there is no need for the macro that casts to `Py_UCS1`. 
I also inlined several functions that were previously shared between SequenceRecord and BytesSequenceRecord. Which is now redundant.
I think this makes the code more readable.
=> Small pointer refactor and cleanup

README.rst, doc/api.rst, doc/conf.py, doc/tutorial.rst, src/dnaio/__init__.py, src/dnaio/_core.pyx, src/dnaio/interfaces.py, src/dnaio/pairedend.py, src/dnaio/readers.py, src/dnaio/singleend.py, src/dnaio/writers.py
A couple of cleanup commits:
- Document Reader and Writer interfaces and `records_are_mates`
- Some API documentation cleanup
- Factor out `_open_paired`
- Type hint corrections
I think this should close #56.
=> API documentation improvements (and some other minor things)

CHANGES.rst
Hi, I tried to release dnaio on my own since you are on holiday. It seems as I don't have permissions though. (I wanted to push to main and add a v0.9.1 tag). No matter. I think I can help the user by providing the wheel directly. I made this PR so the changelog work does not need to be duplicated. See you after the holiday!
=> Version 0.9.1

src/dnaio/_core.pyx, src/dnaio/exceptions.py, src/dnaio/readers.py
Raise it when an attempt is made to create a SequenceRecord with non-ASCII characters in one of the fields.
This is backwards compatible because `IsNotAscii` is a subclass of `ValueError`, which was previously raised for this type of problem.
Also, catch the exception in the FastaReader and convert it to a FastaFormatError when it occurs.
This will help in solving https://github.com/marcelm/cutadapt/issues/628.
=> Consistently raise FastaFormatError on parse errors

.github/workflows/ci.yml, tox.ini
I noticed that Codecov.io didn’t have coverage reports. The changes here should make it work again.
=> Upload again code coverage reports to Codecov.io

tests/test_internal.py
The warning is:
> PytestRemovedIn8Warning: Support for nose tests is deprecated and will be removed in a future release.
> [...] is using nose-specific method: `setup(self)` To remove this warning, rename it to `setup_method(self)`
> See docs: https://docs.pytest.org/en/stable/deprecations.html#support-for-tests-written-for-nose
=> Avoid pytest 7.2 warnings

CHANGES.rst, src/dnaio/_core.pyx
Before:
```
Benchmark 1: python dnaio_read.py ~/test/big2.fastq
Time (mean ± σ):     914.5 ms ±  23.8 ms    [User: 792.7 ms, System: 121.7 ms]
Range (min … max):   882.0 ms … 950.4 ms    10 runs
```
After:
```
Benchmark 1: python dnaio_read.py ~/test/big2.fastq
Time (mean ± σ):     752.6 ms ±  14.0 ms    [User: 628.9 ms, System: 123.5 ms]
Range (min … max):   725.8 ms … 779.4 ms    10 runs
```
The disadvantage is that we break `__new__` for everyone. Is this a problem for cutadapt? `__init__` works fine.
The speed advantage requires some explanation. Using the CPython API there are two methods you can set on your extension class: `tp_new` and `tp_init`. `tp_new` creates the class and `tp_init` initializes it. Most extension classes have however, no dynamic attributes so do not need …
=> Faster SequenceRecord initialization.

.github/workflows/ci.yml
Jobs are triggered twice if they are pushed to the repo and if they are part of a pull request. With this, a job belonging to a pull request is only run if it comes from a forked repository.
Derived from
https://wildwolf.name/github-actions-how-to-avoid-running-the-same-workflow-multiple-times/, (but typos fixed)
(It would be nicer if GitHub just handled this automatically.)
=> Avoid running CI jobs twice

CHANGES.rst, src/dnaio/__init__.py
A very minor addition to the open function, but making it much more convenient. Compatibility with cutadapt is kept.
This fixes #90 . 
Discussion points:
- compresslevel vs compression_level. I think that compresslevel is not a very good abbreviation, on the other hand it is used consistently throughout CPython (and also xopen). Since dnaio is not a compression library I think the non-abbreviated version is better here.
- open_threads 0 by default. As someone who regularly works on a compute cluster I am regularly annoyed by applications that by default use all threads or a lot of them. One reason is that when I start a simple script/program on the login node this shouldn't immediately drain all the CPUs if I haven't told it so. This makes the login node unusable, so in my mind the only …
=> Allow setting open_threads and compression_level

.readthedocs.yaml
This will be required soon, see https://blog.readthedocs.com/use-build-os-config/
=> Add build.os key to Read the Docs configuration

.github/workflows/ci.yml
Also, do not build wheels for Python 3.7 as it is end of life.
I tested this locally with this command:
```bash
CIBW_SKIP="cp37-*" CIBW_BUILD="cp*-manylinux_x86_64 cp3*-win_amd64 cp3*-macosx_x86_64" pipx run cibuildwheel==2.16.2 --platform=linux
```
which created these wheels:
```
dnaio-1.0.1.dev9+g7420fee-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl   93 kB
dnaio-1.0.1.dev9+g7420fee-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl   94 kB
dnaio-1.0.1.dev9+g7420fee-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl   91 kB
dnaio-1.0.1.dev9+g7420fee-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl     94 kB
dnaio-1.0.1.dev9+g7420fee-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl     94 kB
```
=> Bump cibuildwheel so that wheels for Python 3.12 get built

tox.ini
None were found. Unfortunately the environment cannot run on github CI. This might be useful for some of your other projects. I just managed to remove two memory errors from python-isal. They were in exception paths, nothing major, but still nice.
=> Add asan tox environment for testing memory errors

README.rst, src/dnaio/readers.py
Hi, what a fantastically useful library this is! I particularly like that it supports stdin and Zstandard compression.
This tiny PR highlights underlying xopen's (and therefore dnaio's) existing support for `.zst` extensions, mentioning that either of two dependencies (`zstd` CLI or `Zstandard` PyPI package) must be installed to make it work.
=> Highlight xopen's Zstandard support when optionally installed

src/dnaio/_core.pyx
This is inconsequential except that it leads to slightly cleaner code and slightly cleaner assembly. In this case the compiler will turn it into a direct comparison of two 16 bit integers, rather than comparing the characters individually. 
Since the branch is very predictable, there is no performance impact.
=> Using memcmp with a fixed length leads to very efficient assembly

CITATION.cff, README.rst
This adds a `CITATION.cff` file. I used Zenodo to generate DOIs.
The DOI listed in `CITATION.cff` and linked to in the badge is the "all versions" DOI: https://zenodo.org/doi/10.5281/zenodo.10548864
The DOI specific to version 1.2.0 is this one: https://zenodo.org/doi/10.5281/zenodo.10548865
Zenodo recommends using the more specific one, but I am reluctant to do so because that would require that we update the `CITATION.cff` file for each release, and also that we enable GitHub releases.
CC @DongzeHE 
Closes #127
=> Add citation info

.github/workflows/ci.yml
https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
We should also generate wheels at some point, but cibuildwheel only has preliminary support for it; we can wait a little bit.
=> Run tests on the M1 macOS runner

.github/workflows/ci.yml, pyproject.toml, src/dnaio/bam.h
See: https://github.com/samtools/htslib/pull/1764
Using dispatch is less flaky than precompiling with SSSE3 instructions. It will work on any machine.
I made the dispatching work properly with GCC. I also used the basic nibble2base function in htslib as a base for the default. 
From prior discussion in htslib I learned that deoding the qualities can be easily optimized by the compiler including the tricks to do so.
=> Use dispatch rather than rely on separate compile commands for SSSE3 bam parser

.github/workflows/ci.yml
Also:
- Fix codecov uploads
- Bump upload-action (and ensure unique artifact names, which is now a requirement)
- Test on both macos-13 (x86_64) and macos-14 (arm64)
Successful run (with the check whether CI is running for a tag commented out): https://github.com/marcelm/dnaio/actions/runs/8800496451
=> Build macOS arm64 wheels

src/dnaio/ascii_check.h
Rewriting it to use `size_t` will create the most optimal code for all platofrms. Also I did a small optimization that works well for small strings. 
Say if the string is length 13. Previously the function would check 8 bytes at once, then check 5 bytes individually. What I do now is simply substract 8 from the length and check an 8 byte vector at the end. This is much more optimal for smaller strings. 
Not that we need that, as we check 128kb chunks. But it eliminates a loop from the function, so might as well leave it in. 
The 8byte loop is unrolled to do 4 OR operations simultaneously. This is automatically compiled to do two SSE2 OR operations with `-O2` on GCC. As a result this code is not slower than the code that it replaces with had vectors inserted manually. 
The resulting code …
=> Rewrite ascii check to allow compiler auto vectorization

src/dnaio/bam.h
Two improvements coming from htslib. Credit for simplifying the bam decode goes to @jmarshall. 
See: https://github.com/samtools/htslib/pull/1795
For the use of constructor:
https://github.com/samtools/htslib/pull/1786
Using the constructor attribute makes the code simpler. Another change is that the fallback code now also always use a function pointer and cannot inline. This also makes the code simpler.
=> Decode BAM sequence with less code. Dispatch function at dynamic link time rather than at run time. 

src/dnaio/multipleend.py
The original error:
```
src/dnaio/multipleend.py:205: error: Argument 1 to "enter_context" of "ExitStack" has incompatible type "Any | str | PathLike[Any] | BinaryIO"; expected "AbstractContextManager[IO[Any], bool | None]"  [arg-type]
Found 1 error in 1 file (checked 12 source files
```
=> Ignore complex mypy issue

src/dnaio/_core.pyx
Debian's linting tool "lintian" reports the below informational message in dnaio 1.2.2 (and possibly other versions):
I: python3-dnaio: spelling-error-in-binary "allows to" "allows one to" [usr/lib/python3/dist-packages/dnaio/_core.cpython-312-x86_64-linux-gnu.so]
This patch applies almost blindly the recommendation, although perhaps there exists better wording to apply to the desctiption of the symbol. For what it's worth, I did attempt to find better wording, but lacking proper context for the function, the recommended change might do.
=> s/d/_core.pyx: pedantic typo caught by linting.

.github/workflows/ci.yml, CHANGES.rst, README.rst, pyproject.toml, tox.ini
I’d like to make Python 3.13 wheels available. I suggest to merge this PR and then release 1.2.3.
=> Support Python 3.13; drop support for Python 3.8

.github/workflows/ci.yml, src/dnaio/singleend.py
Python 3.10 is fine, but 3.11 breaks the tests. This made creating the wheels for v1.2.3 fail.
=> Fix failing test on Windows with Python 3.11.9+

.readthedocs.yaml
https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/
=> Fix Read the Docs configuration

pyproject.toml
setuptools starting from version 75.7.0 changed how CFLAGS work: They no longer are added to the CFLAGS Python was compiled with, but replace them.
With this change, our CFLAGS of `-g0 -DNDEBUG` get used directly and the wheels are compiled without proper optimizations because `-O2` is missing.
Within cibuildwheel, the Python compiler options that we "lose" by this change are:
-fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall
Of these, we really only require `-O3` and `-DNDEBUG`, so the easiest fix should be to just add `-O3` to the CFLAGS that we provide.
Found by @rhpvorderman in https://github.com/marcelm/cutadapt/issues/843
=> Fix unoptimized wheels
